2013-03-14 17:03:43: DEBUG: log file: test//test_20130314_1603/master.logger.txt
2013-03-14 17:03:43: DEBUG: server: minotauro
2013-03-14 17:03:43: INFO: + avast: INIT
2013-03-14 17:03:43: INFO: + mcafee: INIT
2013-03-14 17:03:43: INFO: + panda: INIT
2013-03-14 17:03:43: INFO: + pctools: INIT
2013-03-14 17:03:43: INFO: + sophos: INIT
2013-03-14 17:03:43: INFO: + comodo: INIT
2013-03-14 17:03:43: INFO: + drweb: INIT
2013-03-14 17:03:43: INFO: + eset: INIT
2013-03-14 17:03:43: INFO: + emsisoft: INIT
2013-03-14 17:03:43: INFO: + avira: INIT
2013-03-14 17:03:43: INFO: + fsecure: INIT
2013-03-14 17:03:43: INFO: + gdata: INIT
2013-03-14 17:03:43: INFO: + msessential: INIT
2013-03-14 17:03:43: INFO: + norton: INIT
2013-03-14 17:03:43: INFO: + trendm: INIT
2013-03-14 17:03:43: INFO: + avg: INIT
2013-03-14 17:03:43: INFO: + bitdef: INIT
2013-03-14 17:03:43: INFO: + zoneal: INIT
2013-03-14 17:03:43: INFO: + ahnlab: INIT
2013-03-14 17:03:43: INFO: + comodo: INIT
2013-03-14 17:03:43: INFO: + norman: INIT
2013-03-14 17:03:43: INFO: + kis: INIT
2013-03-14 17:03:52: INFO: logging in
2013-03-14 17:03:52: INFO: Win7-Comodo, ERROR: Problem running login_in_guest. Reason: [InvalidPowerStateFault]: The attempted operation cannot be performed in the current state (Powered off).
2013-03-14 17:03:52: INFO: ok. logged in
2013-03-14 17:03:52: INFO: Win7-Comodo, ERROR: Problem running start_process. Reason: [Invalid Operation]: You must call first login_in_guest
2013-03-14 17:03:52: DEBUG: created process c:\WINDOWS\system32\calc.exe with pid None
2013-03-14 17:03:52: INFO: Win7-Comodo, ERROR: Problem running list_processes. Reason: [Invalid Operation]: You must call first login_in_guest
2013-03-14 17:03:52: ERROR: Traceback (most recent call last):
2013-03-14 17:03:52: ERROR:   File "master.py", line 463, in <module>
2013-03-14 17:03:52: ERROR: main()
2013-03-14 17:03:52: ERROR:   File "master.py", line 409, in main
2013-03-14 17:03:52: ERROR: test(args)
2013-03-14 17:03:52: ERROR:   File "master.py", line 326, in test
2013-03-14 17:03:52: ERROR: vsphere.execute_cmd(vm, "c:\\WINDOWS\\system32\\calc.exe")
2013-03-14 17:03:52: ERROR:   File "/Users/olli/Documents/work/AVTest/AVMaster/lib/SphereManager.py", line 109, in execute_cmd
2013-03-14 17:03:52: ERROR: while pid in self.get_all_pid(vm):
2013-03-14 17:03:52: ERROR:   File "/Users/olli/Documents/work/AVTest/AVMaster/lib/SphereManager.py", line 96, in get_all_pid
2013-03-14 17:03:52: ERROR: for proc in procs:
2013-03-14 17:03:52: ERROR: TypeError
2013-03-14 17:03:52: ERROR: :
2013-03-14 17:03:52: ERROR: 'NoneType' object is not iterable
